name: Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0" # Run weekly

jobs:
  security:
    name: Security scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version-file: "go.mod"

      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-file: "go.mod"
          check-latest: true

      - name: Run gosec
        uses: securego/gosec@master
        with:
          args: ./...

      - name: Install nancy
        run: go install github.com/sonatype-nexus-community/nancy@latest

      - name: Run nancy
        run: go list -json -deps | nancy sleuth
